{
"0":{"fieldName":"xsid","fieldNameCh":"学生编号","ShowMaxLength":"40","isPK":"1","isShow":"0","isSelect":"0","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","keyTableID":""},
"1":{"fieldName":"njid","fieldNameCh":"年级","ShowMaxLength":"6","isPK":"0","isShow":"1","isSelect":"1","isIntType":"0","isFK":"1","FKTableName":"GradeInfo","FKTablePK":"njid","FKTableField":"njmc","keyTableID":""},
"2":{"fieldName":"bjid","fieldNameCh":"班级","ShowMaxLength":"6","isPK":"0","isShow":"1","isSelect":"1","isIntType":"0","isFK":"1","FKTableName":"ClassInfo","FKTablePK":"bjid","FKTableField":"bjmc","keyTableID":""},
"3":{"fieldName":"xh","fieldNameCh":"学号","ShowMaxLength":"9","isPK":"0","isShow":"1","isSelect":"1","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","keyTableID":""},
"4":{"fieldName":"mm","fieldNameCh":"密码","ShowMaxLength":"0","isPK":"0","isShow":"0","isSelect":"0","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","keyTableID":""},
"5":{"fieldName":"sfz","fieldNameCh":"身份证","ShowMaxLength":"18","isPK":"0","isShow":"1","isSelect":"1","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","keyTableID":""},
"6":{"fieldName":"csrq","fieldNameCh":"出身日期","ShowMaxLength":"10","isPK":"0","isShow":"1","isSelect":"1","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","keyTableID":""},
"7":{"fieldName":"dh","fieldNameCh":"电话","ShowMaxLength":"11","isPK":"0","isShow":"1","isSelect":"1","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","keyTableID":""},
"8":{"fieldName":"qq","fieldNameCh":"QQ号码","ShowMaxLength":"9","isPK":"0","isShow":"1","isSelect":"1","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","keyTableID":""},
"9":{"fieldName":"yx","fieldNameCh":"邮箱","ShowMaxLength":"10","isPK":"0","isShow":"1","isSelect":"1","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","keyTableID":""},
"10":{"fieldName":"dz","fieldNameCh":"地址","ShowMaxLength":"10","isPK":"0","isShow":"1","isSelect":"1","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","keyTableID":""},
"11":{"fieldName":"zp","fieldNameCh":"照片","ShowMaxLength":"10","isPK":"0","isShow":"0","isSelect":"0","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","keyTableID":""},
"12":{"fieldName":"xb","fieldNameCh":"性别","ShowMaxLength":"2","isPK":"0","isShow":"1","isSelect":"1","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","keyTableID":"36cfb0d1-449a-444c-bc21-5d9c9dbe56f4"},
"13":{"fieldName":"xl","fieldNameCh":"学历","ShowMaxLength":"4","isPK":"0","isShow":"1","isSelect":"1","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","keyTableID":"2142d3da-be3a-43bf-bdce-3fb6abe5f9ad"}
}



{
"0":{"fieldName":"xsid","fieldNameCh":"学生编号","isPK":"1","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","regexTypeID":"all","editTypeID":"0","regrxText":"学生编号","keyTableID":"","isEdit":"0","EditMinLength":"0","EditMaxLength":"40","isMust":"1"},
"1":{"fieldName":"njid","fieldNameCh":"年级","isPK":"0","isIntType":"0","isFK":"1","FKTableName":"GradeInfo","FKTablePK":"njid","FKTableField":"njmc","regexTypeID":"all","editTypeID":"3","regrxText":"选择学生所在的年级","keyTableID":"","isEdit":"1","EditMinLength":"0","EditMaxLength":"40","isMust":"1"},
"2":{"fieldName":"bjid","fieldNameCh":"班级","isPK":"0","isIntType":"0","isFK":"1","FKTableName":"ClassInfo","FKTablePK":"bjid","FKTableField":"bjmc","regexTypeID":"all","editTypeID":"3","regrxText":"选择学生所在的班级","keyTableID":"","isEdit":"1","EditMinLength":"0","EditMaxLength":"40","isMust":"1"},
"3":{"fieldName":"xh","fieldNameCh":"学号","isPK":"0","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","regexTypeID":"num","editTypeID":"1","regrxText":"学生的学号","keyTableID":"","isEdit":"1","EditMinLength":"6","EditMaxLength":"10","isMust":"1"},
"4":{"fieldName":"mm","fieldNameCh":"密码","isPK":"0","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","regexTypeID":"username","editTypeID":"4","regrxText":"输入登陆时的密码","keyTableID":"","isEdit":"1","EditMinLength":"6","EditMaxLength":"16","isMust":"1"},
"5":{"fieldName":"sfz","fieldNameCh":"身份证","isPK":"0","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","regexTypeID":"idcard","editTypeID":"1","regrxText":"学生的身份证号码","keyTableID":"","isEdit":"1","EditMinLength":"15","EditMaxLength":"18","isMust":"0"},
"6":{"fieldName":"csrq","fieldNameCh":"出身日期","isPK":"0","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","regexTypeID":"all","editTypeID":"2","regrxText":"选择一个出身日期","keyTableID":"","isEdit":"1","EditMinLength":"0","EditMaxLength":"20","isMust":"0"},
"7":{"fieldName":"dh","fieldNameCh":"电话","isPK":"0","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","regexTypeID":"tel","editTypeID":"1","regrxText":"学生的手机/电话号码","keyTableID":"","isEdit":"1","EditMinLength":"3","EditMaxLength":"13","isMust":"0"},
"8":{"fieldName":"qq","fieldNameCh":"QQ号码","isPK":"0","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","regexTypeID":"qq","editTypeID":"1","regrxText":"学生的QQ号码","keyTableID":"","isEdit":"1","EditMinLength":"6","EditMaxLength":"10","isMust":"0"},
"9":{"fieldName":"yx","fieldNameCh":"邮箱","isPK":"0","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","regexTypeID":"email","editTypeID":"1","regrxText":"邮箱地址","keyTableID":"","isEdit":"1","EditMinLength":"5","EditMaxLength":"30","isMust":"0"},
"10":{"fieldName":"dz","fieldNameCh":"地址","isPK":"0","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","regexTypeID":"all","editTypeID":"1","regrxText":"家庭地址","keyTableID":"","isEdit":"1","EditMinLength":"8","EditMaxLength":"60","isMust":"0"},
"11":{"fieldName":"zp","fieldNameCh":"照片","isPK":"0","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","regexTypeID":"picture","editTypeID":"5","regrxText":"个人照片","keyTableID":"","isEdit":"1","EditMinLength":"0","EditMaxLength":"100","isMust":"0"},
"12":{"fieldName":"xb","fieldNameCh":"性别","isPK":"0","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","regexTypeID":"all","editTypeID":"3","regrxText":"性别","keyTableID":"36cfb0d1-449a-444c-bc21-5d9c9dbe56f4","isEdit":"1","EditMinLength":"0","EditMaxLength":"2","isMust":"1"},
"13":{"fieldName":"xl","fieldNameCh":"学历","isPK":"0","isIntType":"0","isFK":"0","FKTableName":"","FKTablePK":"","FKTableField":"","regexTypeID":"all","editTypeID":"3","regrxText":"学历","keyTableID":"2142d3da-be3a-43bf-bdce-3fb6abe5f9ad","isEdit":"1","EditMinLength":"0","EditMaxLength":"4","isMust":"1"}
}